import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../componenet/Navbar";
import Footer from '../componenet/Footer';
import {StateContext} from "../context/StateContext";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Ecommerce App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body>
        <StateContext>
          <Toaster />
          <header className='main-container'>
            <Navbar />
          </header>
          {children}
          <footer>
            <Footer />
          </footer>
        </StateContext>
      </body>
    </html>
  );
}